#!/bin/bash

# Script d'installation de pip-mode dans le profil shell
# Usage: ./scripts/install-pip-mode.sh

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
PIP_MODE_SCRIPT="$PROJECT_ROOT/scripts/pip-mode.sh"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 Installation de pip-mode"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Détecter le shell
if [ -n "$ZSH_VERSION" ]; then
    SHELL_NAME="zsh"
    PROFILE_FILE="$HOME/.zshrc"
elif [ -n "$BASH_VERSION" ]; then
    SHELL_NAME="bash"
    PROFILE_FILE="$HOME/.bashrc"
else
    echo "⚠️  Shell non reconnu. Installation manuelle requise."
    exit 1
fi

echo "Shell détecté: $SHELL_NAME"
echo "Fichier de profil: $PROFILE_FILE"
echo ""

# Vérifier que le script pip-mode existe
if [ ! -f "$PIP_MODE_SCRIPT" ]; then
    echo "❌ Erreur: $PIP_MODE_SCRIPT non trouvé"
    exit 1
fi

# Vérifier si pip-mode est déjà installé
if grep -q "pip-mode.sh" "$PROFILE_FILE" 2>/dev/null; then
    echo "✓ pip-mode est déjà configuré dans $PROFILE_FILE"
    echo ""
    read -p "Voulez-vous réinstaller ? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation annulée."
        exit 0
    fi

    # Supprimer l'ancienne configuration
    echo "Suppression de l'ancienne configuration..."
    sed -i.bak '/# pip-mode configuration/,/# End pip-mode configuration/d' "$PROFILE_FILE"
fi

# Ajouter la configuration
echo "Ajout de pip-mode à $PROFILE_FILE..."
cat >> "$PROFILE_FILE" << EOF

# pip-mode configuration
# Auto-generated by $0 on $(date)
if [ -f "$PIP_MODE_SCRIPT" ]; then
    source "$PIP_MODE_SCRIPT"
    alias pip-mode='pip_mode'
fi
# End pip-mode configuration
EOF

echo "✓ Configuration ajoutée avec succès"
echo ""

# Test de la configuration
echo "Test de l'installation..."
if source "$PROFILE_FILE" && type pip_mode &>/dev/null; then
    echo "✓ pip-mode installé avec succès !"
    echo ""
    echo "Pour utiliser pip-mode :"
    echo "  1. Recharger votre shell : source $PROFILE_FILE"
    echo "  2. Utiliser la commande : pip-mode status"
    echo ""
else
    echo "⚠️  Installation réussie mais test échoué"
    echo "   Rechargez manuellement : source $PROFILE_FILE"
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Commandes disponibles :"
echo "  pip-mode status   - Vérifier la configuration"
echo "  pip-mode nexus    - Basculer vers Nexus"
echo "  pip-mode standard - Basculer vers PyPI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Documentation : $PROJECT_ROOT/docs/pip-mode-guide.md"
